/gazebo_ros_control:
  pid_gains:
    ur3_arm_shoulder_pan_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur3_arm_shoulder_lift_joint:
      p: 100.0
      i: 0.01 
      d: 10.0  
    ur3_arm_elbow_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur3_arm_wrist_1_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur3_arm_wrist_2_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur3_arm_wrist_3_joint:
      p: 100.0
      i: 0.01 
